name: 'Public Infrastructure Action PoC'
description:
  'A proof of concept for GitHub workflow-to-workflow interactions, outputs, and
  results.'
author: 'Your name or organization here'

outputs:
  result:
    description:
      The return value of the script, stringified with `JSON.stringify`

runs:
  using: node20
  main: dist/index.js
