name: 'Public Infrastructure Action PoC'
description:
  'A proof of concept for GitHub workflow-to-workflow interactions, outputs, and
  results.'
author: 'Your name or organization here'

# There should be one output for each prior job. Each output name is a string with the previous job name.

runs:
  using: node20
  main: dist/index.js
