name: 'Public Infrastructure Action PoC'
description:
  'A proof of concept for GitHub workflow-to-workflow interactions, outputs, and
  results.'
author: 'Your name or organization here'

outputs:
  needs_outputs:
    description:
      The output of any jobs listed as a dependency of this job under `needs`.
      This is stringified with `JSON.stringify`.

runs:
  using: node20
  main: dist/index.js
