name: 'Public Infrastructure Action PoC'
description:
  'A proof of concept for GitHub workflow-to-workflow interactions, outputs, and
  results.'
author: 'Your name or organization here'

# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
