name: 'Public Infrastructure Action PoC'
description:
  'A proof of concept for GitHub workflow-to-workflow interactions, outputs, and
  results.'
author: 'Your name or organization here'

inputs:
  ref:
    description: The name of the commit/branch/tag.
    required: true

# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
